version: "3.7"
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: timetracker
      POSTGRES_PASSWORD: timetracker
      POSTGRES_DB: timetracker
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
