version: "2"
services:
  timetracker-api:
    build: .
    environment:
      - PG_DB=timetracker
    volumes:
      - .:/app
    ports:
      - "3010:3010"
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres
    restart: always
